# Generated by Django 3.2.5 on 2022-01-31 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Class',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('upload', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='ML')),
            ],
            options={
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('weight', models.IntegerField(blank=True, db_column='weight', default=1, null=True)),
            ],
            options={
                'db_table': 'Test',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, db_column='address', max_length=150)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, db_column='gender', max_length=100, null=True)),
                ('image', models.ImageField(db_column='image', null=True, upload_to='student')),
                ('description', models.CharField(blank=True, db_column='description', max_length=2550, null=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=255, null=True)),
                ('dob', models.DateTimeField(blank=True, db_column='dob', max_length=255, null=True)),
                ('classid', models.ForeignKey(db_column='ClassID', on_delete=django.db.models.deletion.DO_NOTHING, to='center.class')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('semester', models.CharField(blank=True, db_column='semester', max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, db_column='time', max_length=255, null=True)),
                ('score', models.FloatField(blank=True, db_column='score', max_length=255, null=True)),
                ('student', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='center.student')),
                ('subject', models.ForeignKey(db_column='SubjectID', on_delete=django.db.models.deletion.CASCADE, to='center.subject')),
                ('testid', models.ForeignKey(db_column='TestID', on_delete=django.db.models.deletion.DO_NOTHING, to='center.test')),
            ],
            options={
                'db_table': 'Result',
            },
        ),
    ]
