# Generated by Django 3.2.5 on 2022-01-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(db_column='file', null=True, upload_to='file')),
            ],
            options={
                'db_table': 'ExcelFile',
            },
        ),
    ]
