# Generated by Django 3.2.5 on 2022-01-24 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_excelfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelFile',
        ),
    ]
