# Generated by Django 3.2.5 on 2022-01-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_auto_20220124_1632'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='Document',
        ),
    ]
